team_id: fwe3dwe2jiuefjr4

# default_workspace_path: agents-space/team_run_tyqwge6712
default_workspace_path: 

agents:
  - id: agent1
    
    # config_file_path: config/agent1.json
    config_file_path: 
    
    # workspace_path: agents-space/n_tyqwge6712_adasdwq
    workspace_path: 
    
    use_workspace_default: true

  - id: agent2123
    
    # config_file_path: config/agent1.json
    config_file_path: 
    
    # workspace_path: agents-space/n_tyqwge6712_adasdwq
    workspace_path: 
    
    use_workspace_default: false

  - id: agent14123
    
    # config_file_path: config/agent1.json
    config_file_path: 
    
    # workspace_path: agents-space/n_tyqwge6712_adasdwq
    workspace_path: 
    
    use_workspace_default: true


metadata:
  version: "1.0"
  created_at: "2025-11-06"
  description: Простая команда из нескольких агентов